Repository MongoEngine/flask-mongoengine, pull requests merged in 2020-06, with the labels that each got.

#380 Update setup.py: Remove setup_requirements
  setup.py
Labels: log:changed, topic: CI/CD

#392 Remove some not project-related labels
  .github/labels.yml
Labels: log:skip-changelog

#393 Remove six dependency (Drop Python 2.7 compatibility)
  flask_mongoengine/wtf/fields.py
  requirements.txt
  setup.py
Labels: log:changed, topic: code style

#394 Github Actions CI/CD tests for project
  .github/workflows/main.yml
  .travis.yml
  tox.ini
Labels: log:added, topic: CI/CD

#343 Pass 'places' to 'precision' in wtfForms DecimalField convertation
  flask_mongoengine/wtf/orm.py
Labels: log:fixed, type: enhancement

#348 Added label_modifier option on ReferenceField conversion
  flask_mongoengine/wtf/fields.py
  flask_mongoengine/wtf/orm.py
  tests/test_forms.py
Labels: log:added, type: enhancement

#387 Fix formdata default value on ModelForm <-> FlaskForm inheritance.
  flask_mongoengine/wtf/models.py
Labels: log:fixed, type: enhancement

#395 Remove python 2.7 artefacts
  docs/conf.py
  docs/index.rst
  examples/simpleapp/app.py
  flask_mongoengine/__init__.py
  flask_mongoengine/pagination.py
  setup.py
Labels: log:skip-changelog, topic: code style

#398 Replace general Exception raising with more detailed type
  codecov.yml
  flask_mongoengine/__init__.py
Labels: log:changed, type: enhancement

#397 Tests refactoring. Moving to pytest engine
  README.rst
  requirements-dev.txt
  setup.cfg
  setup.py
  tests/__init__.py
  tests/conftest.py
  tests/test_base.py
  tests/test_basic_app.py
  tests/test_connection.py
  tests/test_forms.py
  tests/test_json.py
  tests/test_json_app.py
  tests/test_pagination.py
  tests/test_session.py
  tox.ini
Labels: log:changed, type: enhancement

#401 Allow keep config in MongoEngine object until init_app
  flask_mongoengine/__init__.py
Labels: log:changed, type: enhancement
