Repository MongoEngine/flask-mongoengine, pull requests merged in 2020-12, with the labels that each got.

#423 Add python_requires to setup.py to fix #421
  setup.py
Labels: log:fixed, type: bug

#427 Debug toolbar extended with current mongoengine commands
  flask_mongoengine/operation_tracker.py
  flask_mongoengine/templates/panels/mongo-panel.html
Labels: log:added

#428 Fixed some quotes in pagination file
  flask_mongoengine/pagination.py
Labels: log:fixed

#431 Code style adjusted in sessions.py and __init__.py slightly simplified
  flask_mongoengine/__init__.py
  flask_mongoengine/sessions.py
  flask_mongoengine/wtf/orm.py
Labels: log:changed

#432 Adjust pytest to show missing coverage
  setup.cfg
Labels: log:changed, topic: CI/CD, topic: tests

#434 Debug panel source code simplified
  flask_mongoengine/operation_tracker.py
  flask_mongoengine/panels.py
Labels: log:changed, topic: code style

#433 Extended sessions.py tests
  requirements-dev.txt
  tests/test_session.py
  tox.ini
Labels: log:changed, topic: tests
