Repository MongoEngine/flask-mongoengine, pull requests merged in 2022-07, with the labels that each got.

#452 CI/CD pipeline errors fixed
  .github/workflows/linting.yml
  .pre-commit-config.yaml
  pyproject.toml
  requirements-dev.txt
  tests/test_connection.py
Labels: topic: CI/CD, log:fixed

#455 Removed: Python 3.6 official support (EOL), Added python 3.10 support
  .github/workflows/main.yml
  setup.py
  tox.ini
Labels: topic: CI/CD, type: breaking-change, log:added, log:removed

#456 Some simple code polishing in project files
  flask_mongoengine/connection.py
  flask_mongoengine/operation_tracker.py
  flask_mongoengine/wtf/orm.py
Labels: topic: code style

#458 All authors credits restored from gitlog
  AUTHORS
  LICENSE.md
  MANIFEST.in
  credits.md
  docs/LICENSE.md
  docs/credits.md
  docs/index.rst
Labels: topic: documentation, log:fixed

#459 Authors part 2
  AUTHORS.md
  LICENSE.md
  MANIFEST.in
  credits.md
  docs/AUTHORS.md
  docs/LICENSE.md
  docs/index.rst
Labels: log:skip-changelog

#460 Added concrete readthedocs config and related workflow requirement
  .readthedocs.yaml
Labels: topic: CI/CD, log:added

#461 Update github actions versions to latest available
  .github/workflows/coverage.yml
  .github/workflows/drafter.yml
  .github/workflows/labeler-check.yml
  .github/workflows/labeler.yml
  .github/workflows/linting.yml
  .github/workflows/tests.yml
Labels: topic: CI/CD, log:changed

#463 Added: Isort CI/CD helper and configuration
  .pre-commit-config.yaml
  docs/conf.py
  examples/simpleapp/app.py
  flask_mongoengine/connection.py
  flask_mongoengine/sessions.py
  flask_mongoengine/wtf/orm.py
  pyproject.toml
  setup.py
  tests/test_base.py
Labels: topic: CI/CD, log:added

#464 Replace strings interpolation with f-strings in project tests
  tests/test_basic_app.py
  tests/test_forms.py
  tests/test_json_app.py
  tests/test_pagination.py
  tests/test_session.py
Labels: topic: tests, log:changed

#444 flask-mongoengine now using flask internal json encoder
  flask_mongoengine/wtf/fields.py
Labels: log:fixed

#466 Allow bypass coverage upload without an error
  .github/workflows/coverage.yml
Labels: topic: CI/CD, log:fixed

#439 FIXED: BaseQuerySet.get_or_404 use 'message' keyword argument for Document searching
  docs/api/base.rst
  docs/conf.py
  flask_mongoengine/__init__.py
Labels: log:fixed

#435 FIXED: Configuration retrieve order
  flask_mongoengine/__init__.py
Labels: log:fixed

#422 FIXED: Use the accurate total number in Pagination, respecting limit() cases
  flask_mongoengine/pagination.py
Labels: log:fixed

#437 FIXED #436: Omit CSRF token when populating model instance with form data
  flask_mongoengine/wtf/models.py
  tests/test_forms.py
Labels: log:fixed

#445 Encode DBRef and ObjectId
  flask_mongoengine/json.py
  tests/test_json_app.py
Labels: log:added

#345 ADDED: Support for FileField
  flask_mongoengine/wtf/orm.py
  tests/test_forms.py
Labels: type: breaking-change, log:added

#470 Added concrete code climate config
  .codeclimate.yml
Labels: topic: CI/CD, log:added

#472 Ugly silent mongoengine patching replaced with explicit inheritance, mixins and attributes bypass(for backward compatibility)
  docs/api/wtf.rst
  flask_mongoengine/__init__.py
  flask_mongoengine/wtf/__init__.py
  flask_mongoengine/wtf/base.py
  flask_mongoengine/wtf/db_fields.py
  flask_mongoengine/wtf/orm.py
  setup.py
Labels: type: breaking-change, log:breaking-change, log:changed

#473 Fixed: Tests database left on test server. (Added session level cleanup)
  tests/conftest.py
  tests/test_connection.py
Labels: topic: tests, log:fixed

#467 Debug toolbar replaced with new version, based on pymongo monitoring
  docs/_static/debug_toolbar.png
  docs/_static/debugtoolbar.png
  docs/api/base.rst
  docs/api/wtf.rst
  docs/conf.py
  docs/debug_toolbar.md
  example_app/app.py
  example_app/views.py
  flask_mongoengine/operation_tracker.py
  flask_mongoengine/panels.py
  flask_mongoengine/templates/panels/mongo-panel.html
  requirements.txt
  setup.py
  tests/test_debug_panel.py
Labels: type: breaking-change, type: feature, log:breaking-change

#474 CI/CD Test matrix extended to test all mongo db versions and re-check minimum supported requirements
  .github/workflows/coverage.yml
  .github/workflows/linting.yml
  .github/workflows/tests.yml
  .gitignore
  noxfile.py
  requirements-dev.txt
  setup.cfg
  setup.py
  tox.ini
Labels: topic: CI/CD, log:changed

#475 Added: Complete pyproject.toml configuration; Removed: Static version mentions in source code files
  .gitignore
  .readthedocs.yaml
  docs/conf.py
  docs/requirements.txt
  example_app/compose/flask/Dockerfile
  flask_mongoengine/__init__.py
  noxfile.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  setup.cfg
  setup.py
Labels: topic: code style, topic: CI/CD, log:added, log:removed

#429 Rewrite connection module
  flask_mongoengine/__init__.py
  flask_mongoengine/connection.py
  tests/conftest.py
  tests/test_connection.py
  tests/test_json.py
Labels: type: enhancement, type: breaking-change, log:breaking-change, log:fixed, stage: WIP

#477 New README.md; New CONTRIBUTING.md; New Flask configuration documentation section
  CONTRIBUTING.md
  CONTRIBUTING.rst
  MANIFEST.in
  README.md
  README.rst
  docs/CONTRIBUTING.md
  docs/basics.md
  docs/flask_config.md
  docs/index.rst
  example_app/app.py
  example_app/views.py
  flask_mongoengine/__init__.py
  flask_mongoengine/connection.py
  noxfile.py
  pyproject.toml
Labels: topic: documentation, log:added

#478 Make WTFForms completely optional
  example_app/compose/flask/Dockerfile
  flask_mongoengine/__init__.py
  flask_mongoengine/wtf/__init__.py
  tests/test_forms.py
Labels: log:changed

#479 Added: support for json parse of aggregation cursor
  AUTHORS.md
  flask_mongoengine/json.py
  tests/test_json_app.py
Labels: log:added

#480 Fixed: db_fields.py docstrings typos
  flask_mongoengine/connection.py
  flask_mongoengine/pagination.py
  flask_mongoengine/wtf/__init__.py
  flask_mongoengine/wtf/db_fields.py
Labels: log:skip-changelog

#481 Restricted: passing arguments on fields definition in WTF compatible mode (Fixes: #379)
  example_app/app.py
  flask_mongoengine/wtf/db_fields.py
  tests/conftest.py
  tests/test_debug_panel.py
  tests/test_forms.py
Labels: log:added, log:breaking-change

#485 Improved: Pagination performance
  flask_mongoengine/pagination.py
  tests/test_pagination.py
Labels: log:changed

#486 Added: Intersphinx integrations with wtforms and flask-wtf
  docs/conf.py
Labels: topic: documentation, log:added

#487 Addede: Pillow requirement for testing ImageField
  pyproject.toml
Labels: topic: CI/CD, log:added

#488 Changed: Example app view style
  example_app/app.py
  example_app/compose/flask/Dockerfile
  example_app/models.py
  example_app/static/style.css
  example_app/templates/index.html
  example_app/templates/layout.html
  example_app/templates/pagination.html
  example_app/views.py
Labels: log:changed

#489 Updated: ORM module functions split for better maintenance
  flask_mongoengine/__init__.py
  flask_mongoengine/db_fields.py
  flask_mongoengine/decorators.py
  flask_mongoengine/wtf/__init__.py
  flask_mongoengine/wtf/models.py
  flask_mongoengine/wtf/orm.py
Labels: log:changed

#490 Addede: db_fields file tests
  tests/test_db_fields.py
  tests/test_db_fields_import_protection.py
Labels: log:added

#491 Deprecated: ORM module and forms generation with model_form, model_fields
  flask_mongoengine/decorators.py
  flask_mongoengine/wtf/orm.py
  tests/test_decorators.py
Labels: log:deprecated

#493 CI/CD: Ignore arguments count issues
  .codeclimate.yml
Labels: topic: CI/CD, log:changed

#494 CI/CD: Include pip update to nox sessions
  noxfile.py
Labels: topic: CI/CD, topic: tests, log:added

#496 Added: Tests to check correct work without extra install options, or part of them
  .github/workflows/coverage.yml
  noxfile.py
  tests/test_db_fields.py
  tests/test_db_fields_import_protection.py
  tests/test_debug_panel.py
  tests/test_forms.py
Labels: topic: tests, log:added

#497 New model form generator: Support of StringField based fields
  docs/forms.md
  example_app/app.py
  example_app/strings_demo.py
  example_app/templates/layout.html
  example_app/templates/strings_demo.html
  example_app/views.py
  flask_mongoengine/db_fields.py
  flask_mongoengine/wtf/fields.py
  pyproject.toml
  tests/test_db_fields.py
  tests/test_forms_v2.py
Labels: log:added
